version: '3'
services:
  scraping-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: scraping-server
    container_name: scraping-server

    ports:
      - "9999:9999"

    environment:
      - URL=
      - KEYWORD=

    volumes:
      - ./server/src:/src
      - "./server/test:/test"

    networks:
      - scraping-network

    working_dir: /src

    tty: true

    depends_on: 
      - redis

    command: ['/bin/bash', '-c', 'uvicorn api_server:app --reload --host 0.0.0.0 --port 9999']

  redis:
    image: redis:6.2.6
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379

    networks:
      - scraping-network

  ### If use Image-Scraping-Web, uncomment below
  web:
    build:
      context: ./Image-Scraping-Web
      dockerfile: Dockerfile
    image: scraping-web
    container_name: scraping-web

    ports:
      - "3000:3000"
    
    tty: true
  
volumes:
  redis-volume:

networks:
  scraping-network:
    name: scraping-network
