version: '3'
services:
  scraping-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: scraping-server
    container_name: scraping-server

    ports:
      - "9999:9999"

    environment:
      - URL=
      - KEYWORD=

    volumes:
      - ./server/src:/src
      - "./server/test:/test"

    working_dir: /src

    tty: true

    # command: ['/bin/bash', '-c', 'python scraping.py $$URL --keyword $$KEYWORD']
    command: ['/bin/bash', '-c', 'uvicorn api_server:app --reload --host 0.0.0.0 --port 9999']